language: cpp

sudo: not required

compilers:
  - gcc
  - clang

os:
  - linux

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make install

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

matrix:
  include:
    - os: linux
      compiler: clang

# Don't send e-mail notifications
notifications:
  email: false
