  /// \file test.cc
/*
 *
 * test.cc source template automatically generated by a class generator
 * Creation date : ven. f�vr. 24 2017
 *
 * This file is part of Monkey libraries.
 *
 * Monkey is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Monkey is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Monkey.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Remi Ete
 * @copyright Remi Ete
 */

#include <iostream>
#include <monkey/monkey.h>

int main()
{
  monkey::Node root;
  root.insert("bibou", 3.8);
  root.insert("pouette", "A string");
  root.insert("The answer", 42);
  root.insert("The boubou", "cacahuette");
  std::cout << "Root type : " << root.type() << std::endl;
  std::cout << "Root size : " << root.size() << std::endl;

  const monkey::Node &bibou(root["bibou"]);
  std::cout << "Bibou type : " << bibou.type() << std::endl;

  for(auto iter = root.begin() ; iter != root.end() ; ++iter)
    std::cout << "-> '" << iter->first << "' : " << iter->second.as<std::string>() << std::endl;

  return 0;
}
