#################################################
# cmake file for building Monkey files converters
# @author Rémi Eté
# Copyright (c) Rémi Eté
#################################################

MACRO( CONVERT_FILE_EXECUTABLE _format1 _format2 )

  STRING( TOLOWER ${format1} FORMAT1_TOLOWER )
  STRING( TOLOWER ${format2} FORMAT2_TOLOWER )

  SET(CONVERT_FILE_FORMAT_1 ${_format1} )
  SET(CONVERT_FILE_FORMAT_2 ${_format2} )
  SET(CONVERT_EXECUTABLE_NAME "monkey-${FORMAT1_TOLOWER}-to-${FORMAT2_TOLOWER}" )

  CONFIGURE_FILE( "${PROJECT_SOURCE_DIR}/source/main/convert-files.cc.in"
  "${PROJECT_BINARY_DIR}/${CONVERT_EXECUTABLE_NAME}.cc" @ONLY )

  ADD_EXECUTABLE( ${CONVERT_EXECUTABLE_NAME} ${PROJECT_BINARY_DIR}/${CONVERT_EXECUTABLE_NAME}.cc )
  TARGET_LINK_LIBRARIES( ${CONVERT_EXECUTABLE_NAME} ${PROJECT_NAME} )

  INSTALL(
          TARGETS ${CONVERT_EXECUTABLE_NAME}
          RUNTIME DESTINATION bin
  )

  SET(CONVERT_FILE_FORMAT_2 ${_format1} )
  SET(CONVERT_FILE_FORMAT_1 ${_format2} )
  SET(CONVERT_EXECUTABLE_NAME "monkey-${FORMAT2_TOLOWER}-to-${FORMAT1_TOLOWER}" )

  CONFIGURE_FILE( "${PROJECT_SOURCE_DIR}/source/main/convert-files.cc.in"
  "${PROJECT_BINARY_DIR}/${CONVERT_EXECUTABLE_NAME}.cc" @ONLY )

  ADD_EXECUTABLE( ${CONVERT_EXECUTABLE_NAME} ${PROJECT_BINARY_DIR}/${CONVERT_EXECUTABLE_NAME}.cc )
  TARGET_LINK_LIBRARIES( ${CONVERT_EXECUTABLE_NAME} ${PROJECT_NAME} )

  INSTALL(
          TARGETS ${CONVERT_EXECUTABLE_NAME}
          RUNTIME DESTINATION bin
  )

ENDMACRO()
